package com.panhai.business.device.declaration.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ServiceApplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public ServiceApplyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andApplyCIsNull() {
            addCriterion("apply_c is null");
            return (Criteria) this;
        }

        public Criteria andApplyCIsNotNull() {
            addCriterion("apply_c is not null");
            return (Criteria) this;
        }

        public Criteria andApplyCEqualTo(String value) {
            addCriterion("apply_c =", value, "applyC");
            return (Criteria) this;
        }

        public Criteria andApplyCNotEqualTo(String value) {
            addCriterion("apply_c <>", value, "applyC");
            return (Criteria) this;
        }

        public Criteria andApplyCGreaterThan(String value) {
            addCriterion("apply_c >", value, "applyC");
            return (Criteria) this;
        }

        public Criteria andApplyCGreaterThanOrEqualTo(String value) {
            addCriterion("apply_c >=", value, "applyC");
            return (Criteria) this;
        }

        public Criteria andApplyCLessThan(String value) {
            addCriterion("apply_c <", value, "applyC");
            return (Criteria) this;
        }

        public Criteria andApplyCLessThanOrEqualTo(String value) {
            addCriterion("apply_c <=", value, "applyC");
            return (Criteria) this;
        }

        public Criteria andApplyCLike(String value) {
            addCriterion("apply_c like", value, "applyC");
            return (Criteria) this;
        }

        public Criteria andApplyCNotLike(String value) {
            addCriterion("apply_c not like", value, "applyC");
            return (Criteria) this;
        }

        public Criteria andApplyCIn(List<String> values) {
            addCriterion("apply_c in", values, "applyC");
            return (Criteria) this;
        }

        public Criteria andApplyCNotIn(List<String> values) {
            addCriterion("apply_c not in", values, "applyC");
            return (Criteria) this;
        }

        public Criteria andApplyCBetween(String value1, String value2) {
            addCriterion("apply_c between", value1, value2, "applyC");
            return (Criteria) this;
        }

        public Criteria andApplyCNotBetween(String value1, String value2) {
            addCriterion("apply_c not between", value1, value2, "applyC");
            return (Criteria) this;
        }

        public Criteria andApplyTypeCIsNull() {
            addCriterion("apply_type_c is null");
            return (Criteria) this;
        }

        public Criteria andApplyTypeCIsNotNull() {
            addCriterion("apply_type_c is not null");
            return (Criteria) this;
        }

        public Criteria andApplyTypeCEqualTo(String value) {
            addCriterion("apply_type_c =", value, "applyTypeC");
            return (Criteria) this;
        }

        public Criteria andApplyTypeCNotEqualTo(String value) {
            addCriterion("apply_type_c <>", value, "applyTypeC");
            return (Criteria) this;
        }

        public Criteria andApplyTypeCGreaterThan(String value) {
            addCriterion("apply_type_c >", value, "applyTypeC");
            return (Criteria) this;
        }

        public Criteria andApplyTypeCGreaterThanOrEqualTo(String value) {
            addCriterion("apply_type_c >=", value, "applyTypeC");
            return (Criteria) this;
        }

        public Criteria andApplyTypeCLessThan(String value) {
            addCriterion("apply_type_c <", value, "applyTypeC");
            return (Criteria) this;
        }

        public Criteria andApplyTypeCLessThanOrEqualTo(String value) {
            addCriterion("apply_type_c <=", value, "applyTypeC");
            return (Criteria) this;
        }

        public Criteria andApplyTypeCLike(String value) {
            addCriterion("apply_type_c like", value, "applyTypeC");
            return (Criteria) this;
        }

        public Criteria andApplyTypeCNotLike(String value) {
            addCriterion("apply_type_c not like", value, "applyTypeC");
            return (Criteria) this;
        }

        public Criteria andApplyTypeCIn(List<String> values) {
            addCriterion("apply_type_c in", values, "applyTypeC");
            return (Criteria) this;
        }

        public Criteria andApplyTypeCNotIn(List<String> values) {
            addCriterion("apply_type_c not in", values, "applyTypeC");
            return (Criteria) this;
        }

        public Criteria andApplyTypeCBetween(String value1, String value2) {
            addCriterion("apply_type_c between", value1, value2, "applyTypeC");
            return (Criteria) this;
        }

        public Criteria andApplyTypeCNotBetween(String value1, String value2) {
            addCriterion("apply_type_c not between", value1, value2, "applyTypeC");
            return (Criteria) this;
        }

        public Criteria andApplyDeviceCodeCIsNull() {
            addCriterion("apply_device_code_c is null");
            return (Criteria) this;
        }

        public Criteria andApplyDeviceCodeCIsNotNull() {
            addCriterion("apply_device_code_c is not null");
            return (Criteria) this;
        }

        public Criteria andApplyDeviceCodeCEqualTo(String value) {
            addCriterion("apply_device_code_c =", value, "applyDeviceCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDeviceCodeCNotEqualTo(String value) {
            addCriterion("apply_device_code_c <>", value, "applyDeviceCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDeviceCodeCGreaterThan(String value) {
            addCriterion("apply_device_code_c >", value, "applyDeviceCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDeviceCodeCGreaterThanOrEqualTo(String value) {
            addCriterion("apply_device_code_c >=", value, "applyDeviceCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDeviceCodeCLessThan(String value) {
            addCriterion("apply_device_code_c <", value, "applyDeviceCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDeviceCodeCLessThanOrEqualTo(String value) {
            addCriterion("apply_device_code_c <=", value, "applyDeviceCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDeviceCodeCLike(String value) {
            addCriterion("apply_device_code_c like", value, "applyDeviceCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDeviceCodeCNotLike(String value) {
            addCriterion("apply_device_code_c not like", value, "applyDeviceCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDeviceCodeCIn(List<String> values) {
            addCriterion("apply_device_code_c in", values, "applyDeviceCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDeviceCodeCNotIn(List<String> values) {
            addCriterion("apply_device_code_c not in", values, "applyDeviceCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDeviceCodeCBetween(String value1, String value2) {
            addCriterion("apply_device_code_c between", value1, value2, "applyDeviceCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDeviceCodeCNotBetween(String value1, String value2) {
            addCriterion("apply_device_code_c not between", value1, value2, "applyDeviceCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDepartmentCodeCIsNull() {
            addCriterion("apply_department_code_c is null");
            return (Criteria) this;
        }

        public Criteria andApplyDepartmentCodeCIsNotNull() {
            addCriterion("apply_department_code_c is not null");
            return (Criteria) this;
        }

        public Criteria andApplyDepartmentCodeCEqualTo(String value) {
            addCriterion("apply_department_code_c =", value, "applyDepartmentCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDepartmentCodeCNotEqualTo(String value) {
            addCriterion("apply_department_code_c <>", value, "applyDepartmentCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDepartmentCodeCGreaterThan(String value) {
            addCriterion("apply_department_code_c >", value, "applyDepartmentCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDepartmentCodeCGreaterThanOrEqualTo(String value) {
            addCriterion("apply_department_code_c >=", value, "applyDepartmentCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDepartmentCodeCLessThan(String value) {
            addCriterion("apply_department_code_c <", value, "applyDepartmentCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDepartmentCodeCLessThanOrEqualTo(String value) {
            addCriterion("apply_department_code_c <=", value, "applyDepartmentCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDepartmentCodeCLike(String value) {
            addCriterion("apply_department_code_c like", value, "applyDepartmentCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDepartmentCodeCNotLike(String value) {
            addCriterion("apply_department_code_c not like", value, "applyDepartmentCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDepartmentCodeCIn(List<String> values) {
            addCriterion("apply_department_code_c in", values, "applyDepartmentCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDepartmentCodeCNotIn(List<String> values) {
            addCriterion("apply_department_code_c not in", values, "applyDepartmentCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDepartmentCodeCBetween(String value1, String value2) {
            addCriterion("apply_department_code_c between", value1, value2, "applyDepartmentCodeC");
            return (Criteria) this;
        }

        public Criteria andApplyDepartmentCodeCNotBetween(String value1, String value2) {
            addCriterion("apply_department_code_c not between", value1, value2, "applyDepartmentCodeC");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceTypeCIsNull() {
            addCriterion("implement_place_type_c is null");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceTypeCIsNotNull() {
            addCriterion("implement_place_type_c is not null");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceTypeCEqualTo(String value) {
            addCriterion("implement_place_type_c =", value, "implementPlaceTypeC");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceTypeCNotEqualTo(String value) {
            addCriterion("implement_place_type_c <>", value, "implementPlaceTypeC");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceTypeCGreaterThan(String value) {
            addCriterion("implement_place_type_c >", value, "implementPlaceTypeC");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceTypeCGreaterThanOrEqualTo(String value) {
            addCriterion("implement_place_type_c >=", value, "implementPlaceTypeC");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceTypeCLessThan(String value) {
            addCriterion("implement_place_type_c <", value, "implementPlaceTypeC");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceTypeCLessThanOrEqualTo(String value) {
            addCriterion("implement_place_type_c <=", value, "implementPlaceTypeC");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceTypeCLike(String value) {
            addCriterion("implement_place_type_c like", value, "implementPlaceTypeC");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceTypeCNotLike(String value) {
            addCriterion("implement_place_type_c not like", value, "implementPlaceTypeC");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceTypeCIn(List<String> values) {
            addCriterion("implement_place_type_c in", values, "implementPlaceTypeC");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceTypeCNotIn(List<String> values) {
            addCriterion("implement_place_type_c not in", values, "implementPlaceTypeC");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceTypeCBetween(String value1, String value2) {
            addCriterion("implement_place_type_c between", value1, value2, "implementPlaceTypeC");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceTypeCNotBetween(String value1, String value2) {
            addCriterion("implement_place_type_c not between", value1, value2, "implementPlaceTypeC");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceMIsNull() {
            addCriterion("implement_place_m is null");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceMIsNotNull() {
            addCriterion("implement_place_m is not null");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceMEqualTo(String value) {
            addCriterion("implement_place_m =", value, "implementPlaceM");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceMNotEqualTo(String value) {
            addCriterion("implement_place_m <>", value, "implementPlaceM");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceMGreaterThan(String value) {
            addCriterion("implement_place_m >", value, "implementPlaceM");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceMGreaterThanOrEqualTo(String value) {
            addCriterion("implement_place_m >=", value, "implementPlaceM");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceMLessThan(String value) {
            addCriterion("implement_place_m <", value, "implementPlaceM");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceMLessThanOrEqualTo(String value) {
            addCriterion("implement_place_m <=", value, "implementPlaceM");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceMLike(String value) {
            addCriterion("implement_place_m like", value, "implementPlaceM");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceMNotLike(String value) {
            addCriterion("implement_place_m not like", value, "implementPlaceM");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceMIn(List<String> values) {
            addCriterion("implement_place_m in", values, "implementPlaceM");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceMNotIn(List<String> values) {
            addCriterion("implement_place_m not in", values, "implementPlaceM");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceMBetween(String value1, String value2) {
            addCriterion("implement_place_m between", value1, value2, "implementPlaceM");
            return (Criteria) this;
        }

        public Criteria andImplementPlaceMNotBetween(String value1, String value2) {
            addCriterion("implement_place_m not between", value1, value2, "implementPlaceM");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIsNull() {
            addCriterion("apply_user_id is null");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIsNotNull() {
            addCriterion("apply_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdEqualTo(String value) {
            addCriterion("apply_user_id =", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotEqualTo(String value) {
            addCriterion("apply_user_id <>", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdGreaterThan(String value) {
            addCriterion("apply_user_id >", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("apply_user_id >=", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLessThan(String value) {
            addCriterion("apply_user_id <", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLessThanOrEqualTo(String value) {
            addCriterion("apply_user_id <=", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLike(String value) {
            addCriterion("apply_user_id like", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotLike(String value) {
            addCriterion("apply_user_id not like", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIn(List<String> values) {
            addCriterion("apply_user_id in", values, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotIn(List<String> values) {
            addCriterion("apply_user_id not in", values, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdBetween(String value1, String value2) {
            addCriterion("apply_user_id between", value1, value2, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotBetween(String value1, String value2) {
            addCriterion("apply_user_id not between", value1, value2, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyDtIsNull() {
            addCriterion("apply_dt is null");
            return (Criteria) this;
        }

        public Criteria andApplyDtIsNotNull() {
            addCriterion("apply_dt is not null");
            return (Criteria) this;
        }

        public Criteria andApplyDtEqualTo(Date value) {
            addCriterionForJDBCDate("apply_dt =", value, "applyDt");
            return (Criteria) this;
        }

        public Criteria andApplyDtNotEqualTo(Date value) {
            addCriterionForJDBCDate("apply_dt <>", value, "applyDt");
            return (Criteria) this;
        }

        public Criteria andApplyDtGreaterThan(Date value) {
            addCriterionForJDBCDate("apply_dt >", value, "applyDt");
            return (Criteria) this;
        }

        public Criteria andApplyDtGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("apply_dt >=", value, "applyDt");
            return (Criteria) this;
        }

        public Criteria andApplyDtLessThan(Date value) {
            addCriterionForJDBCDate("apply_dt <", value, "applyDt");
            return (Criteria) this;
        }

        public Criteria andApplyDtLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("apply_dt <=", value, "applyDt");
            return (Criteria) this;
        }

        public Criteria andApplyDtIn(List<Date> values) {
            addCriterionForJDBCDate("apply_dt in", values, "applyDt");
            return (Criteria) this;
        }

        public Criteria andApplyDtNotIn(List<Date> values) {
            addCriterionForJDBCDate("apply_dt not in", values, "applyDt");
            return (Criteria) this;
        }

        public Criteria andApplyDtBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("apply_dt between", value1, value2, "applyDt");
            return (Criteria) this;
        }

        public Criteria andApplyDtNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("apply_dt not between", value1, value2, "applyDt");
            return (Criteria) this;
        }

        public Criteria andUrgentTypeCIsNull() {
            addCriterion("urgent_type_c is null");
            return (Criteria) this;
        }

        public Criteria andUrgentTypeCIsNotNull() {
            addCriterion("urgent_type_c is not null");
            return (Criteria) this;
        }

        public Criteria andUrgentTypeCEqualTo(String value) {
            addCriterion("urgent_type_c =", value, "urgentTypeC");
            return (Criteria) this;
        }

        public Criteria andUrgentTypeCNotEqualTo(String value) {
            addCriterion("urgent_type_c <>", value, "urgentTypeC");
            return (Criteria) this;
        }

        public Criteria andUrgentTypeCGreaterThan(String value) {
            addCriterion("urgent_type_c >", value, "urgentTypeC");
            return (Criteria) this;
        }

        public Criteria andUrgentTypeCGreaterThanOrEqualTo(String value) {
            addCriterion("urgent_type_c >=", value, "urgentTypeC");
            return (Criteria) this;
        }

        public Criteria andUrgentTypeCLessThan(String value) {
            addCriterion("urgent_type_c <", value, "urgentTypeC");
            return (Criteria) this;
        }

        public Criteria andUrgentTypeCLessThanOrEqualTo(String value) {
            addCriterion("urgent_type_c <=", value, "urgentTypeC");
            return (Criteria) this;
        }

        public Criteria andUrgentTypeCLike(String value) {
            addCriterion("urgent_type_c like", value, "urgentTypeC");
            return (Criteria) this;
        }

        public Criteria andUrgentTypeCNotLike(String value) {
            addCriterion("urgent_type_c not like", value, "urgentTypeC");
            return (Criteria) this;
        }

        public Criteria andUrgentTypeCIn(List<String> values) {
            addCriterion("urgent_type_c in", values, "urgentTypeC");
            return (Criteria) this;
        }

        public Criteria andUrgentTypeCNotIn(List<String> values) {
            addCriterion("urgent_type_c not in", values, "urgentTypeC");
            return (Criteria) this;
        }

        public Criteria andUrgentTypeCBetween(String value1, String value2) {
            addCriterion("urgent_type_c between", value1, value2, "urgentTypeC");
            return (Criteria) this;
        }

        public Criteria andUrgentTypeCNotBetween(String value1, String value2) {
            addCriterion("urgent_type_c not between", value1, value2, "urgentTypeC");
            return (Criteria) this;
        }

        public Criteria andPhenomenonDescXIsNull() {
            addCriterion("phenomenon_desc_x is null");
            return (Criteria) this;
        }

        public Criteria andPhenomenonDescXIsNotNull() {
            addCriterion("phenomenon_desc_x is not null");
            return (Criteria) this;
        }

        public Criteria andPhenomenonDescXEqualTo(String value) {
            addCriterion("phenomenon_desc_x =", value, "phenomenonDescX");
            return (Criteria) this;
        }

        public Criteria andPhenomenonDescXNotEqualTo(String value) {
            addCriterion("phenomenon_desc_x <>", value, "phenomenonDescX");
            return (Criteria) this;
        }

        public Criteria andPhenomenonDescXGreaterThan(String value) {
            addCriterion("phenomenon_desc_x >", value, "phenomenonDescX");
            return (Criteria) this;
        }

        public Criteria andPhenomenonDescXGreaterThanOrEqualTo(String value) {
            addCriterion("phenomenon_desc_x >=", value, "phenomenonDescX");
            return (Criteria) this;
        }

        public Criteria andPhenomenonDescXLessThan(String value) {
            addCriterion("phenomenon_desc_x <", value, "phenomenonDescX");
            return (Criteria) this;
        }

        public Criteria andPhenomenonDescXLessThanOrEqualTo(String value) {
            addCriterion("phenomenon_desc_x <=", value, "phenomenonDescX");
            return (Criteria) this;
        }

        public Criteria andPhenomenonDescXLike(String value) {
            addCriterion("phenomenon_desc_x like", value, "phenomenonDescX");
            return (Criteria) this;
        }

        public Criteria andPhenomenonDescXNotLike(String value) {
            addCriterion("phenomenon_desc_x not like", value, "phenomenonDescX");
            return (Criteria) this;
        }

        public Criteria andPhenomenonDescXIn(List<String> values) {
            addCriterion("phenomenon_desc_x in", values, "phenomenonDescX");
            return (Criteria) this;
        }

        public Criteria andPhenomenonDescXNotIn(List<String> values) {
            addCriterion("phenomenon_desc_x not in", values, "phenomenonDescX");
            return (Criteria) this;
        }

        public Criteria andPhenomenonDescXBetween(String value1, String value2) {
            addCriterion("phenomenon_desc_x between", value1, value2, "phenomenonDescX");
            return (Criteria) this;
        }

        public Criteria andPhenomenonDescXNotBetween(String value1, String value2) {
            addCriterion("phenomenon_desc_x not between", value1, value2, "phenomenonDescX");
            return (Criteria) this;
        }

        public Criteria andReceiveDepartmentCIsNull() {
            addCriterion("receive_department_c is null");
            return (Criteria) this;
        }

        public Criteria andReceiveDepartmentCIsNotNull() {
            addCriterion("receive_department_c is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveDepartmentCEqualTo(String value) {
            addCriterion("receive_department_c =", value, "receiveDepartmentC");
            return (Criteria) this;
        }

        public Criteria andReceiveDepartmentCNotEqualTo(String value) {
            addCriterion("receive_department_c <>", value, "receiveDepartmentC");
            return (Criteria) this;
        }

        public Criteria andReceiveDepartmentCGreaterThan(String value) {
            addCriterion("receive_department_c >", value, "receiveDepartmentC");
            return (Criteria) this;
        }

        public Criteria andReceiveDepartmentCGreaterThanOrEqualTo(String value) {
            addCriterion("receive_department_c >=", value, "receiveDepartmentC");
            return (Criteria) this;
        }

        public Criteria andReceiveDepartmentCLessThan(String value) {
            addCriterion("receive_department_c <", value, "receiveDepartmentC");
            return (Criteria) this;
        }

        public Criteria andReceiveDepartmentCLessThanOrEqualTo(String value) {
            addCriterion("receive_department_c <=", value, "receiveDepartmentC");
            return (Criteria) this;
        }

        public Criteria andReceiveDepartmentCLike(String value) {
            addCriterion("receive_department_c like", value, "receiveDepartmentC");
            return (Criteria) this;
        }

        public Criteria andReceiveDepartmentCNotLike(String value) {
            addCriterion("receive_department_c not like", value, "receiveDepartmentC");
            return (Criteria) this;
        }

        public Criteria andReceiveDepartmentCIn(List<String> values) {
            addCriterion("receive_department_c in", values, "receiveDepartmentC");
            return (Criteria) this;
        }

        public Criteria andReceiveDepartmentCNotIn(List<String> values) {
            addCriterion("receive_department_c not in", values, "receiveDepartmentC");
            return (Criteria) this;
        }

        public Criteria andReceiveDepartmentCBetween(String value1, String value2) {
            addCriterion("receive_department_c between", value1, value2, "receiveDepartmentC");
            return (Criteria) this;
        }

        public Criteria andReceiveDepartmentCNotBetween(String value1, String value2) {
            addCriterion("receive_department_c not between", value1, value2, "receiveDepartmentC");
            return (Criteria) this;
        }

        public Criteria andReceiveUserIdIsNull() {
            addCriterion("receive_user_id is null");
            return (Criteria) this;
        }

        public Criteria andReceiveUserIdIsNotNull() {
            addCriterion("receive_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveUserIdEqualTo(String value) {
            addCriterion("receive_user_id =", value, "receiveUserId");
            return (Criteria) this;
        }

        public Criteria andReceiveUserIdNotEqualTo(String value) {
            addCriterion("receive_user_id <>", value, "receiveUserId");
            return (Criteria) this;
        }

        public Criteria andReceiveUserIdGreaterThan(String value) {
            addCriterion("receive_user_id >", value, "receiveUserId");
            return (Criteria) this;
        }

        public Criteria andReceiveUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("receive_user_id >=", value, "receiveUserId");
            return (Criteria) this;
        }

        public Criteria andReceiveUserIdLessThan(String value) {
            addCriterion("receive_user_id <", value, "receiveUserId");
            return (Criteria) this;
        }

        public Criteria andReceiveUserIdLessThanOrEqualTo(String value) {
            addCriterion("receive_user_id <=", value, "receiveUserId");
            return (Criteria) this;
        }

        public Criteria andReceiveUserIdLike(String value) {
            addCriterion("receive_user_id like", value, "receiveUserId");
            return (Criteria) this;
        }

        public Criteria andReceiveUserIdNotLike(String value) {
            addCriterion("receive_user_id not like", value, "receiveUserId");
            return (Criteria) this;
        }

        public Criteria andReceiveUserIdIn(List<String> values) {
            addCriterion("receive_user_id in", values, "receiveUserId");
            return (Criteria) this;
        }

        public Criteria andReceiveUserIdNotIn(List<String> values) {
            addCriterion("receive_user_id not in", values, "receiveUserId");
            return (Criteria) this;
        }

        public Criteria andReceiveUserIdBetween(String value1, String value2) {
            addCriterion("receive_user_id between", value1, value2, "receiveUserId");
            return (Criteria) this;
        }

        public Criteria andReceiveUserIdNotBetween(String value1, String value2) {
            addCriterion("receive_user_id not between", value1, value2, "receiveUserId");
            return (Criteria) this;
        }

        public Criteria andTransferReasonXIsNull() {
            addCriterion("transfer_reason_x is null");
            return (Criteria) this;
        }

        public Criteria andTransferReasonXIsNotNull() {
            addCriterion("transfer_reason_x is not null");
            return (Criteria) this;
        }

        public Criteria andTransferReasonXEqualTo(String value) {
            addCriterion("transfer_reason_x =", value, "transferReasonX");
            return (Criteria) this;
        }

        public Criteria andTransferReasonXNotEqualTo(String value) {
            addCriterion("transfer_reason_x <>", value, "transferReasonX");
            return (Criteria) this;
        }

        public Criteria andTransferReasonXGreaterThan(String value) {
            addCriterion("transfer_reason_x >", value, "transferReasonX");
            return (Criteria) this;
        }

        public Criteria andTransferReasonXGreaterThanOrEqualTo(String value) {
            addCriterion("transfer_reason_x >=", value, "transferReasonX");
            return (Criteria) this;
        }

        public Criteria andTransferReasonXLessThan(String value) {
            addCriterion("transfer_reason_x <", value, "transferReasonX");
            return (Criteria) this;
        }

        public Criteria andTransferReasonXLessThanOrEqualTo(String value) {
            addCriterion("transfer_reason_x <=", value, "transferReasonX");
            return (Criteria) this;
        }

        public Criteria andTransferReasonXLike(String value) {
            addCriterion("transfer_reason_x like", value, "transferReasonX");
            return (Criteria) this;
        }

        public Criteria andTransferReasonXNotLike(String value) {
            addCriterion("transfer_reason_x not like", value, "transferReasonX");
            return (Criteria) this;
        }

        public Criteria andTransferReasonXIn(List<String> values) {
            addCriterion("transfer_reason_x in", values, "transferReasonX");
            return (Criteria) this;
        }

        public Criteria andTransferReasonXNotIn(List<String> values) {
            addCriterion("transfer_reason_x not in", values, "transferReasonX");
            return (Criteria) this;
        }

        public Criteria andTransferReasonXBetween(String value1, String value2) {
            addCriterion("transfer_reason_x between", value1, value2, "transferReasonX");
            return (Criteria) this;
        }

        public Criteria andTransferReasonXNotBetween(String value1, String value2) {
            addCriterion("transfer_reason_x not between", value1, value2, "transferReasonX");
            return (Criteria) this;
        }

        public Criteria andFilePathXIsNull() {
            addCriterion("file_path_x is null");
            return (Criteria) this;
        }

        public Criteria andFilePathXIsNotNull() {
            addCriterion("file_path_x is not null");
            return (Criteria) this;
        }

        public Criteria andFilePathXEqualTo(String value) {
            addCriterion("file_path_x =", value, "filePathX");
            return (Criteria) this;
        }

        public Criteria andFilePathXNotEqualTo(String value) {
            addCriterion("file_path_x <>", value, "filePathX");
            return (Criteria) this;
        }

        public Criteria andFilePathXGreaterThan(String value) {
            addCriterion("file_path_x >", value, "filePathX");
            return (Criteria) this;
        }

        public Criteria andFilePathXGreaterThanOrEqualTo(String value) {
            addCriterion("file_path_x >=", value, "filePathX");
            return (Criteria) this;
        }

        public Criteria andFilePathXLessThan(String value) {
            addCriterion("file_path_x <", value, "filePathX");
            return (Criteria) this;
        }

        public Criteria andFilePathXLessThanOrEqualTo(String value) {
            addCriterion("file_path_x <=", value, "filePathX");
            return (Criteria) this;
        }

        public Criteria andFilePathXLike(String value) {
            addCriterion("file_path_x like", value, "filePathX");
            return (Criteria) this;
        }

        public Criteria andFilePathXNotLike(String value) {
            addCriterion("file_path_x not like", value, "filePathX");
            return (Criteria) this;
        }

        public Criteria andFilePathXIn(List<String> values) {
            addCriterion("file_path_x in", values, "filePathX");
            return (Criteria) this;
        }

        public Criteria andFilePathXNotIn(List<String> values) {
            addCriterion("file_path_x not in", values, "filePathX");
            return (Criteria) this;
        }

        public Criteria andFilePathXBetween(String value1, String value2) {
            addCriterion("file_path_x between", value1, value2, "filePathX");
            return (Criteria) this;
        }

        public Criteria andFilePathXNotBetween(String value1, String value2) {
            addCriterion("file_path_x not between", value1, value2, "filePathX");
            return (Criteria) this;
        }

        public Criteria andApplyStatusIsNull() {
            addCriterion("apply_status is null");
            return (Criteria) this;
        }

        public Criteria andApplyStatusIsNotNull() {
            addCriterion("apply_status is not null");
            return (Criteria) this;
        }

        public Criteria andApplyStatusEqualTo(Short value) {
            addCriterion("apply_status =", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusNotEqualTo(Short value) {
            addCriterion("apply_status <>", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusGreaterThan(Short value) {
            addCriterion("apply_status >", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("apply_status >=", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusLessThan(Short value) {
            addCriterion("apply_status <", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusLessThanOrEqualTo(Short value) {
            addCriterion("apply_status <=", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusIn(List<Short> values) {
            addCriterion("apply_status in", values, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusNotIn(List<Short> values) {
            addCriterion("apply_status not in", values, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusBetween(Short value1, Short value2) {
            addCriterion("apply_status between", value1, value2, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusNotBetween(Short value1, Short value2) {
            addCriterion("apply_status not between", value1, value2, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteIIsNull() {
            addCriterion("delete_i is null");
            return (Criteria) this;
        }

        public Criteria andDeleteIIsNotNull() {
            addCriterion("delete_i is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteIEqualTo(String value) {
            addCriterion("delete_i =", value, "deleteI");
            return (Criteria) this;
        }

        public Criteria andDeleteINotEqualTo(String value) {
            addCriterion("delete_i <>", value, "deleteI");
            return (Criteria) this;
        }

        public Criteria andDeleteIGreaterThan(String value) {
            addCriterion("delete_i >", value, "deleteI");
            return (Criteria) this;
        }

        public Criteria andDeleteIGreaterThanOrEqualTo(String value) {
            addCriterion("delete_i >=", value, "deleteI");
            return (Criteria) this;
        }

        public Criteria andDeleteILessThan(String value) {
            addCriterion("delete_i <", value, "deleteI");
            return (Criteria) this;
        }

        public Criteria andDeleteILessThanOrEqualTo(String value) {
            addCriterion("delete_i <=", value, "deleteI");
            return (Criteria) this;
        }

        public Criteria andDeleteILike(String value) {
            addCriterion("delete_i like", value, "deleteI");
            return (Criteria) this;
        }

        public Criteria andDeleteINotLike(String value) {
            addCriterion("delete_i not like", value, "deleteI");
            return (Criteria) this;
        }

        public Criteria andDeleteIIn(List<String> values) {
            addCriterion("delete_i in", values, "deleteI");
            return (Criteria) this;
        }

        public Criteria andDeleteINotIn(List<String> values) {
            addCriterion("delete_i not in", values, "deleteI");
            return (Criteria) this;
        }

        public Criteria andDeleteIBetween(String value1, String value2) {
            addCriterion("delete_i between", value1, value2, "deleteI");
            return (Criteria) this;
        }

        public Criteria andDeleteINotBetween(String value1, String value2) {
            addCriterion("delete_i not between", value1, value2, "deleteI");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateDtIsNull() {
            addCriterion("create_dt is null");
            return (Criteria) this;
        }

        public Criteria andCreateDtIsNotNull() {
            addCriterion("create_dt is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDtEqualTo(Date value) {
            addCriterion("create_dt =", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotEqualTo(Date value) {
            addCriterion("create_dt <>", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtGreaterThan(Date value) {
            addCriterion("create_dt >", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtGreaterThanOrEqualTo(Date value) {
            addCriterion("create_dt >=", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtLessThan(Date value) {
            addCriterion("create_dt <", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtLessThanOrEqualTo(Date value) {
            addCriterion("create_dt <=", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtIn(List<Date> values) {
            addCriterion("create_dt in", values, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotIn(List<Date> values) {
            addCriterion("create_dt not in", values, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtBetween(Date value1, Date value2) {
            addCriterion("create_dt between", value1, value2, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotBetween(Date value1, Date value2) {
            addCriterion("create_dt not between", value1, value2, "createDt");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIdIsNull() {
            addCriterion("modified_user_id is null");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIdIsNotNull() {
            addCriterion("modified_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIdEqualTo(String value) {
            addCriterion("modified_user_id =", value, "modifiedUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIdNotEqualTo(String value) {
            addCriterion("modified_user_id <>", value, "modifiedUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIdGreaterThan(String value) {
            addCriterion("modified_user_id >", value, "modifiedUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("modified_user_id >=", value, "modifiedUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIdLessThan(String value) {
            addCriterion("modified_user_id <", value, "modifiedUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIdLessThanOrEqualTo(String value) {
            addCriterion("modified_user_id <=", value, "modifiedUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIdLike(String value) {
            addCriterion("modified_user_id like", value, "modifiedUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIdNotLike(String value) {
            addCriterion("modified_user_id not like", value, "modifiedUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIdIn(List<String> values) {
            addCriterion("modified_user_id in", values, "modifiedUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIdNotIn(List<String> values) {
            addCriterion("modified_user_id not in", values, "modifiedUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIdBetween(String value1, String value2) {
            addCriterion("modified_user_id between", value1, value2, "modifiedUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIdNotBetween(String value1, String value2) {
            addCriterion("modified_user_id not between", value1, value2, "modifiedUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedDtIsNull() {
            addCriterion("modified_dt is null");
            return (Criteria) this;
        }

        public Criteria andModifiedDtIsNotNull() {
            addCriterion("modified_dt is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedDtEqualTo(Date value) {
            addCriterion("modified_dt =", value, "modifiedDt");
            return (Criteria) this;
        }

        public Criteria andModifiedDtNotEqualTo(Date value) {
            addCriterion("modified_dt <>", value, "modifiedDt");
            return (Criteria) this;
        }

        public Criteria andModifiedDtGreaterThan(Date value) {
            addCriterion("modified_dt >", value, "modifiedDt");
            return (Criteria) this;
        }

        public Criteria andModifiedDtGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_dt >=", value, "modifiedDt");
            return (Criteria) this;
        }

        public Criteria andModifiedDtLessThan(Date value) {
            addCriterion("modified_dt <", value, "modifiedDt");
            return (Criteria) this;
        }

        public Criteria andModifiedDtLessThanOrEqualTo(Date value) {
            addCriterion("modified_dt <=", value, "modifiedDt");
            return (Criteria) this;
        }

        public Criteria andModifiedDtIn(List<Date> values) {
            addCriterion("modified_dt in", values, "modifiedDt");
            return (Criteria) this;
        }

        public Criteria andModifiedDtNotIn(List<Date> values) {
            addCriterion("modified_dt not in", values, "modifiedDt");
            return (Criteria) this;
        }

        public Criteria andModifiedDtBetween(Date value1, Date value2) {
            addCriterion("modified_dt between", value1, value2, "modifiedDt");
            return (Criteria) this;
        }

        public Criteria andModifiedDtNotBetween(Date value1, Date value2) {
            addCriterion("modified_dt not between", value1, value2, "modifiedDt");
            return (Criteria) this;
        }

        public Criteria andVersionNIsNull() {
            addCriterion("version_n is null");
            return (Criteria) this;
        }

        public Criteria andVersionNIsNotNull() {
            addCriterion("version_n is not null");
            return (Criteria) this;
        }

        public Criteria andVersionNEqualTo(Long value) {
            addCriterion("version_n =", value, "versionN");
            return (Criteria) this;
        }

        public Criteria andVersionNNotEqualTo(Long value) {
            addCriterion("version_n <>", value, "versionN");
            return (Criteria) this;
        }

        public Criteria andVersionNGreaterThan(Long value) {
            addCriterion("version_n >", value, "versionN");
            return (Criteria) this;
        }

        public Criteria andVersionNGreaterThanOrEqualTo(Long value) {
            addCriterion("version_n >=", value, "versionN");
            return (Criteria) this;
        }

        public Criteria andVersionNLessThan(Long value) {
            addCriterion("version_n <", value, "versionN");
            return (Criteria) this;
        }

        public Criteria andVersionNLessThanOrEqualTo(Long value) {
            addCriterion("version_n <=", value, "versionN");
            return (Criteria) this;
        }

        public Criteria andVersionNIn(List<Long> values) {
            addCriterion("version_n in", values, "versionN");
            return (Criteria) this;
        }

        public Criteria andVersionNNotIn(List<Long> values) {
            addCriterion("version_n not in", values, "versionN");
            return (Criteria) this;
        }

        public Criteria andVersionNBetween(Long value1, Long value2) {
            addCriterion("version_n between", value1, value2, "versionN");
            return (Criteria) this;
        }

        public Criteria andVersionNNotBetween(Long value1, Long value2) {
            addCriterion("version_n not between", value1, value2, "versionN");
            return (Criteria) this;
        }

        public Criteria andCheckCIsNull() {
            addCriterion("check_c is null");
            return (Criteria) this;
        }

        public Criteria andCheckCIsNotNull() {
            addCriterion("check_c is not null");
            return (Criteria) this;
        }

        public Criteria andCheckCEqualTo(String value) {
            addCriterion("check_c =", value, "checkC");
            return (Criteria) this;
        }

        public Criteria andCheckCNotEqualTo(String value) {
            addCriterion("check_c <>", value, "checkC");
            return (Criteria) this;
        }

        public Criteria andCheckCGreaterThan(String value) {
            addCriterion("check_c >", value, "checkC");
            return (Criteria) this;
        }

        public Criteria andCheckCGreaterThanOrEqualTo(String value) {
            addCriterion("check_c >=", value, "checkC");
            return (Criteria) this;
        }

        public Criteria andCheckCLessThan(String value) {
            addCriterion("check_c <", value, "checkC");
            return (Criteria) this;
        }

        public Criteria andCheckCLessThanOrEqualTo(String value) {
            addCriterion("check_c <=", value, "checkC");
            return (Criteria) this;
        }

        public Criteria andCheckCLike(String value) {
            addCriterion("check_c like", value, "checkC");
            return (Criteria) this;
        }

        public Criteria andCheckCNotLike(String value) {
            addCriterion("check_c not like", value, "checkC");
            return (Criteria) this;
        }

        public Criteria andCheckCIn(List<String> values) {
            addCriterion("check_c in", values, "checkC");
            return (Criteria) this;
        }

        public Criteria andCheckCNotIn(List<String> values) {
            addCriterion("check_c not in", values, "checkC");
            return (Criteria) this;
        }

        public Criteria andCheckCBetween(String value1, String value2) {
            addCriterion("check_c between", value1, value2, "checkC");
            return (Criteria) this;
        }

        public Criteria andCheckCNotBetween(String value1, String value2) {
            addCriterion("check_c not between", value1, value2, "checkC");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dm_service_apply
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 20 16:18:49 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}