package com.panhai.business.device.declaration.entity;

import java.io.Serializable;
import java.util.Date;

public class ServiceApply implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.id
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.apply_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String applyC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.apply_type_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String applyTypeC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.apply_device_code_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String applyDeviceCodeC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.apply_department_code_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String applyDepartmentCodeC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.implement_place_type_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String implementPlaceTypeC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.implement_place_m
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String implementPlaceM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.apply_user_id
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String applyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.apply_dt
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private Date applyDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.urgent_type_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String urgentTypeC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.phenomenon_desc_x
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String phenomenonDescX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.receive_department_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String receiveDepartmentC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.receive_user_id
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String receiveUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.transfer_reason_x
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String transferReasonX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.file_path_x
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String filePathX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.apply_status
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private Short applyStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.delete_i
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String deleteI;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.create_user_id
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.create_dt
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private Date createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.modified_user_id
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String modifiedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.modified_dt
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private Date modifiedDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.version_n
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private Long versionN;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_service_apply.check_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private String checkC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.id
     *
     * @return the value of dm_service_apply.id
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.id
     *
     * @param id the value for dm_service_apply.id
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.apply_c
     *
     * @return the value of dm_service_apply.apply_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getApplyC() {
        return applyC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.apply_c
     *
     * @param applyC the value for dm_service_apply.apply_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setApplyC(String applyC) {
        this.applyC = applyC == null ? null : applyC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.apply_type_c
     *
     * @return the value of dm_service_apply.apply_type_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getApplyTypeC() {
        return applyTypeC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.apply_type_c
     *
     * @param applyTypeC the value for dm_service_apply.apply_type_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setApplyTypeC(String applyTypeC) {
        this.applyTypeC = applyTypeC == null ? null : applyTypeC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.apply_device_code_c
     *
     * @return the value of dm_service_apply.apply_device_code_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getApplyDeviceCodeC() {
        return applyDeviceCodeC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.apply_device_code_c
     *
     * @param applyDeviceCodeC the value for dm_service_apply.apply_device_code_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setApplyDeviceCodeC(String applyDeviceCodeC) {
        this.applyDeviceCodeC = applyDeviceCodeC == null ? null : applyDeviceCodeC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.apply_department_code_c
     *
     * @return the value of dm_service_apply.apply_department_code_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getApplyDepartmentCodeC() {
        return applyDepartmentCodeC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.apply_department_code_c
     *
     * @param applyDepartmentCodeC the value for dm_service_apply.apply_department_code_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setApplyDepartmentCodeC(String applyDepartmentCodeC) {
        this.applyDepartmentCodeC = applyDepartmentCodeC == null ? null : applyDepartmentCodeC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.implement_place_type_c
     *
     * @return the value of dm_service_apply.implement_place_type_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getImplementPlaceTypeC() {
        return implementPlaceTypeC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.implement_place_type_c
     *
     * @param implementPlaceTypeC the value for dm_service_apply.implement_place_type_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setImplementPlaceTypeC(String implementPlaceTypeC) {
        this.implementPlaceTypeC = implementPlaceTypeC == null ? null : implementPlaceTypeC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.implement_place_m
     *
     * @return the value of dm_service_apply.implement_place_m
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getImplementPlaceM() {
        return implementPlaceM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.implement_place_m
     *
     * @param implementPlaceM the value for dm_service_apply.implement_place_m
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setImplementPlaceM(String implementPlaceM) {
        this.implementPlaceM = implementPlaceM == null ? null : implementPlaceM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.apply_user_id
     *
     * @return the value of dm_service_apply.apply_user_id
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getApplyUserId() {
        return applyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.apply_user_id
     *
     * @param applyUserId the value for dm_service_apply.apply_user_id
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setApplyUserId(String applyUserId) {
        this.applyUserId = applyUserId == null ? null : applyUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.apply_dt
     *
     * @return the value of dm_service_apply.apply_dt
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public Date getApplyDt() {
        return applyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.apply_dt
     *
     * @param applyDt the value for dm_service_apply.apply_dt
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setApplyDt(Date applyDt) {
        this.applyDt = applyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.urgent_type_c
     *
     * @return the value of dm_service_apply.urgent_type_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getUrgentTypeC() {
        return urgentTypeC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.urgent_type_c
     *
     * @param urgentTypeC the value for dm_service_apply.urgent_type_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setUrgentTypeC(String urgentTypeC) {
        this.urgentTypeC = urgentTypeC == null ? null : urgentTypeC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.phenomenon_desc_x
     *
     * @return the value of dm_service_apply.phenomenon_desc_x
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getPhenomenonDescX() {
        return phenomenonDescX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.phenomenon_desc_x
     *
     * @param phenomenonDescX the value for dm_service_apply.phenomenon_desc_x
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setPhenomenonDescX(String phenomenonDescX) {
        this.phenomenonDescX = phenomenonDescX == null ? null : phenomenonDescX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.receive_department_c
     *
     * @return the value of dm_service_apply.receive_department_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getReceiveDepartmentC() {
        return receiveDepartmentC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.receive_department_c
     *
     * @param receiveDepartmentC the value for dm_service_apply.receive_department_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setReceiveDepartmentC(String receiveDepartmentC) {
        this.receiveDepartmentC = receiveDepartmentC == null ? null : receiveDepartmentC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.receive_user_id
     *
     * @return the value of dm_service_apply.receive_user_id
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getReceiveUserId() {
        return receiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.receive_user_id
     *
     * @param receiveUserId the value for dm_service_apply.receive_user_id
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setReceiveUserId(String receiveUserId) {
        this.receiveUserId = receiveUserId == null ? null : receiveUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.transfer_reason_x
     *
     * @return the value of dm_service_apply.transfer_reason_x
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getTransferReasonX() {
        return transferReasonX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.transfer_reason_x
     *
     * @param transferReasonX the value for dm_service_apply.transfer_reason_x
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setTransferReasonX(String transferReasonX) {
        this.transferReasonX = transferReasonX == null ? null : transferReasonX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.file_path_x
     *
     * @return the value of dm_service_apply.file_path_x
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getFilePathX() {
        return filePathX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.file_path_x
     *
     * @param filePathX the value for dm_service_apply.file_path_x
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setFilePathX(String filePathX) {
        this.filePathX = filePathX == null ? null : filePathX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.apply_status
     *
     * @return the value of dm_service_apply.apply_status
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public Short getApplyStatus() {
        return applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.apply_status
     *
     * @param applyStatus the value for dm_service_apply.apply_status
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setApplyStatus(Short applyStatus) {
        this.applyStatus = applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.delete_i
     *
     * @return the value of dm_service_apply.delete_i
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getDeleteI() {
        return deleteI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.delete_i
     *
     * @param deleteI the value for dm_service_apply.delete_i
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setDeleteI(String deleteI) {
        this.deleteI = deleteI == null ? null : deleteI.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.create_user_id
     *
     * @return the value of dm_service_apply.create_user_id
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.create_user_id
     *
     * @param createUserId the value for dm_service_apply.create_user_id
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.create_dt
     *
     * @return the value of dm_service_apply.create_dt
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.create_dt
     *
     * @param createDt the value for dm_service_apply.create_dt
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.modified_user_id
     *
     * @return the value of dm_service_apply.modified_user_id
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getModifiedUserId() {
        return modifiedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.modified_user_id
     *
     * @param modifiedUserId the value for dm_service_apply.modified_user_id
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setModifiedUserId(String modifiedUserId) {
        this.modifiedUserId = modifiedUserId == null ? null : modifiedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.modified_dt
     *
     * @return the value of dm_service_apply.modified_dt
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public Date getModifiedDt() {
        return modifiedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.modified_dt
     *
     * @param modifiedDt the value for dm_service_apply.modified_dt
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setModifiedDt(Date modifiedDt) {
        this.modifiedDt = modifiedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.version_n
     *
     * @return the value of dm_service_apply.version_n
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public Long getVersionN() {
        return versionN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.version_n
     *
     * @param versionN the value for dm_service_apply.version_n
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setVersionN(Long versionN) {
        this.versionN = versionN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_service_apply.check_c
     *
     * @return the value of dm_service_apply.check_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public String getCheckC() {
        return checkC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_service_apply.check_c
     *
     * @param checkC the value for dm_service_apply.check_c
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    public void setCheckC(String checkC) {
        this.checkC = checkC == null ? null : checkC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", applyC=").append(applyC);
        sb.append(", applyTypeC=").append(applyTypeC);
        sb.append(", applyDeviceCodeC=").append(applyDeviceCodeC);
        sb.append(", applyDepartmentCodeC=").append(applyDepartmentCodeC);
        sb.append(", implementPlaceTypeC=").append(implementPlaceTypeC);
        sb.append(", implementPlaceM=").append(implementPlaceM);
        sb.append(", applyUserId=").append(applyUserId);
        sb.append(", applyDt=").append(applyDt);
        sb.append(", urgentTypeC=").append(urgentTypeC);
        sb.append(", phenomenonDescX=").append(phenomenonDescX);
        sb.append(", receiveDepartmentC=").append(receiveDepartmentC);
        sb.append(", receiveUserId=").append(receiveUserId);
        sb.append(", transferReasonX=").append(transferReasonX);
        sb.append(", filePathX=").append(filePathX);
        sb.append(", applyStatus=").append(applyStatus);
        sb.append(", deleteI=").append(deleteI);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", createDt=").append(createDt);
        sb.append(", modifiedUserId=").append(modifiedUserId);
        sb.append(", modifiedDt=").append(modifiedDt);
        sb.append(", versionN=").append(versionN);
        sb.append(", checkC=").append(checkC);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ServiceApply other = (ServiceApply) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getApplyC() == null ? other.getApplyC() == null : this.getApplyC().equals(other.getApplyC()))
            && (this.getApplyTypeC() == null ? other.getApplyTypeC() == null : this.getApplyTypeC().equals(other.getApplyTypeC()))
            && (this.getApplyDeviceCodeC() == null ? other.getApplyDeviceCodeC() == null : this.getApplyDeviceCodeC().equals(other.getApplyDeviceCodeC()))
            && (this.getApplyDepartmentCodeC() == null ? other.getApplyDepartmentCodeC() == null : this.getApplyDepartmentCodeC().equals(other.getApplyDepartmentCodeC()))
            && (this.getImplementPlaceTypeC() == null ? other.getImplementPlaceTypeC() == null : this.getImplementPlaceTypeC().equals(other.getImplementPlaceTypeC()))
            && (this.getImplementPlaceM() == null ? other.getImplementPlaceM() == null : this.getImplementPlaceM().equals(other.getImplementPlaceM()))
            && (this.getApplyUserId() == null ? other.getApplyUserId() == null : this.getApplyUserId().equals(other.getApplyUserId()))
            && (this.getApplyDt() == null ? other.getApplyDt() == null : this.getApplyDt().equals(other.getApplyDt()))
            && (this.getUrgentTypeC() == null ? other.getUrgentTypeC() == null : this.getUrgentTypeC().equals(other.getUrgentTypeC()))
            && (this.getPhenomenonDescX() == null ? other.getPhenomenonDescX() == null : this.getPhenomenonDescX().equals(other.getPhenomenonDescX()))
            && (this.getReceiveDepartmentC() == null ? other.getReceiveDepartmentC() == null : this.getReceiveDepartmentC().equals(other.getReceiveDepartmentC()))
            && (this.getReceiveUserId() == null ? other.getReceiveUserId() == null : this.getReceiveUserId().equals(other.getReceiveUserId()))
            && (this.getTransferReasonX() == null ? other.getTransferReasonX() == null : this.getTransferReasonX().equals(other.getTransferReasonX()))
            && (this.getFilePathX() == null ? other.getFilePathX() == null : this.getFilePathX().equals(other.getFilePathX()))
            && (this.getApplyStatus() == null ? other.getApplyStatus() == null : this.getApplyStatus().equals(other.getApplyStatus()))
            && (this.getDeleteI() == null ? other.getDeleteI() == null : this.getDeleteI().equals(other.getDeleteI()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getCreateDt() == null ? other.getCreateDt() == null : this.getCreateDt().equals(other.getCreateDt()))
            && (this.getModifiedUserId() == null ? other.getModifiedUserId() == null : this.getModifiedUserId().equals(other.getModifiedUserId()))
            && (this.getModifiedDt() == null ? other.getModifiedDt() == null : this.getModifiedDt().equals(other.getModifiedDt()))
            && (this.getVersionN() == null ? other.getVersionN() == null : this.getVersionN().equals(other.getVersionN()))
            && (this.getCheckC() == null ? other.getCheckC() == null : this.getCheckC().equals(other.getCheckC()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getApplyC() == null) ? 0 : getApplyC().hashCode());
        result = prime * result + ((getApplyTypeC() == null) ? 0 : getApplyTypeC().hashCode());
        result = prime * result + ((getApplyDeviceCodeC() == null) ? 0 : getApplyDeviceCodeC().hashCode());
        result = prime * result + ((getApplyDepartmentCodeC() == null) ? 0 : getApplyDepartmentCodeC().hashCode());
        result = prime * result + ((getImplementPlaceTypeC() == null) ? 0 : getImplementPlaceTypeC().hashCode());
        result = prime * result + ((getImplementPlaceM() == null) ? 0 : getImplementPlaceM().hashCode());
        result = prime * result + ((getApplyUserId() == null) ? 0 : getApplyUserId().hashCode());
        result = prime * result + ((getApplyDt() == null) ? 0 : getApplyDt().hashCode());
        result = prime * result + ((getUrgentTypeC() == null) ? 0 : getUrgentTypeC().hashCode());
        result = prime * result + ((getPhenomenonDescX() == null) ? 0 : getPhenomenonDescX().hashCode());
        result = prime * result + ((getReceiveDepartmentC() == null) ? 0 : getReceiveDepartmentC().hashCode());
        result = prime * result + ((getReceiveUserId() == null) ? 0 : getReceiveUserId().hashCode());
        result = prime * result + ((getTransferReasonX() == null) ? 0 : getTransferReasonX().hashCode());
        result = prime * result + ((getFilePathX() == null) ? 0 : getFilePathX().hashCode());
        result = prime * result + ((getApplyStatus() == null) ? 0 : getApplyStatus().hashCode());
        result = prime * result + ((getDeleteI() == null) ? 0 : getDeleteI().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getCreateDt() == null) ? 0 : getCreateDt().hashCode());
        result = prime * result + ((getModifiedUserId() == null) ? 0 : getModifiedUserId().hashCode());
        result = prime * result + ((getModifiedDt() == null) ? 0 : getModifiedDt().hashCode());
        result = prime * result + ((getVersionN() == null) ? 0 : getVersionN().hashCode());
        result = prime * result + ((getCheckC() == null) ? 0 : getCheckC().hashCode());
        return result;
    }
}