package org.ko.data.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.ko.data.bean.Link;
import org.ko.data.bean.LinkExample;

public interface LinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_link
     *
     * @mbg.generated Fri Mar 16 00:14:46 CST 2018
     */
    long countByExample(LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_link
     *
     * @mbg.generated Fri Mar 16 00:14:46 CST 2018
     */
    int deleteByExample(LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_link
     *
     * @mbg.generated Fri Mar 16 00:14:46 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_link
     *
     * @mbg.generated Fri Mar 16 00:14:46 CST 2018
     */
    int insert(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_link
     *
     * @mbg.generated Fri Mar 16 00:14:46 CST 2018
     */
    int insertSelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_link
     *
     * @mbg.generated Fri Mar 16 00:14:46 CST 2018
     */
    List<Link> selectByExampleWithRowbounds(LinkExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_link
     *
     * @mbg.generated Fri Mar 16 00:14:46 CST 2018
     */
    List<Link> selectByExample(LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_link
     *
     * @mbg.generated Fri Mar 16 00:14:46 CST 2018
     */
    Link selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_link
     *
     * @mbg.generated Fri Mar 16 00:14:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") Link record, @Param("example") LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_link
     *
     * @mbg.generated Fri Mar 16 00:14:46 CST 2018
     */
    int updateByExample(@Param("record") Link record, @Param("example") LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_link
     *
     * @mbg.generated Fri Mar 16 00:14:46 CST 2018
     */
    int updateByPrimaryKeySelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_link
     *
     * @mbg.generated Fri Mar 16 00:14:46 CST 2018
     */
    int updateByPrimaryKey(Link record);
}