package com.panhai.business.device.declaration.dao;

import com.panhai.business.device.declaration.entity.ServiceApply;
import com.panhai.business.device.declaration.entity.ServiceApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ServiceApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    long countByExample(ServiceApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    int deleteByExample(ServiceApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    int insert(ServiceApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    int insertSelective(ServiceApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    List<ServiceApply> selectByExampleWithRowbounds(ServiceApplyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    List<ServiceApply> selectByExample(ServiceApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    ServiceApply selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") ServiceApply record, @Param("example") ServiceApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    int updateByExample(@Param("record") ServiceApply record, @Param("example") ServiceApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    int updateByPrimaryKeySelective(ServiceApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_service_apply
     *
     * @mbg.generated Tue Mar 20 16:18:49 CST 2018
     */
    int updateByPrimaryKey(ServiceApply record);
}